#spring:
#  applicaton:
#    name: ad-eureka
#
#server:
#  port: 8000
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: false # 是否从Eureka获取注册信息，这里是单节点server，不需要同步其他eureka server的数据
#    register-with-eureka: false # 这里只有一个server，它本来就是eureka server
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: server1
server:
   port: 8000
eureka:
  instance:
    hostname: server1
    perfer-ip-address: false
  client:
    service-url:
      defaultZone: http://server2:8001/eureka/,http://server3:8002/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: server2
server:
  port: 8001
eureka:
  instance:
    hostname: server2
    perfer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/,http://server3:8002/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: server3
server:
  port: 8002
eureka:
  instance:
    hostname: server3
    perfer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/,http://server2:8001/eureka/